version: "2"
services:
  boxcomtools:
    build: .
    volumes:
      - .:/usr/src/app
    command: adev runserver -p 8080 examples/box_to_smartsheet.py
    environment:
      - BOX_CLIENT_ID=1
      - BOX_CLIENT_SECRET=2
      - SMARTSHEET_CLIENT_ID=3
      - SMARTSHEET_CLIENT_SECRET=4